print ("========== Makanan ==========")
print ("1. Telur Bakar\t\t: Rp. 7.000\n2. Lele Terbang Mas Bhe\t: Rp. 10.000\n3. Es Coklat Lempu\t: Rp. 5.000\n4. Es Doger Langensari\t: Rp. 13.000")
print ("\n========== Pesanan ==========")
tb = int(input("Telur Bakar\t\t: "))
lb = int(input("Lele Terbang Mas Bhe\t: "))
ec = int(input("Es Coklat Lempu\t\t: "))
ed = int(input("Es Doger Langensari\t: "))
print ("\n========== Total ==========")
print (f"Total Telur Bakar {tb} porsi\t\t: Rp. {tb*7000}\nTotal Lele Terbang Mas Bhe {lb} porsi\t: Rp. {lb*10000}\nTotal Es Coklat Lempu {ec} porsi\t\t: Rp. {ec*5000}\nTotal Es Doger Langensari {ed} porsi\t: Rp. {ed*13000}\nTotal Pesanan Anda\t\t\t: Rp. {tb*7000+lb*10000+ec*5000+ed*13000}")